---
- name: Install SonarQube Scanner inside Jenkins container
  hosts: your_ec2_instance  # Change this to your Ansible inventory host
  become: true  # Not needed if running on localhost
  vars:
    sonar_scanner_version: "4.7.0.2747"
    sonar_scanner_url: "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-{{ sonar_scanner_version }}-linux.zip"
    sonar_scanner_dir: "/opt/sonar-scanner"
    jenkins_container_name: "jenkins"  # Change to your Jenkins container name

  tasks:
    - name: Install required packages
      apt:
        name:
          - unzip
        state: present
      become: true  # Use sudo if needed

    - name: Download SonarQube Scanner
      get_url:
        url: "{{ sonar_scanner_url }}"
        dest: "/tmp/sonar-scanner-cli-{{ sonar_scanner_version }}.zip"

    - name: Unzip SonarQube Scanner
      unarchive:
        src: "/tmp/sonar-scanner-cli-{{ sonar_scanner_version }}.zip"
        dest: "/tmp/"
        remote_src: yes

    - name: Move SonarQube Scanner to /opt
      command: mv /tmp/sonar-scanner-{{ sonar_scanner_version }}-linux {{ sonar_scanner_dir }}

    - name: Set up environment variables for the Jenkins container
      command: docker exec jenkins bash -c "echo 'export SONAR_SCANNER_HOME=/opt/sonar-scanner' >> /etc/profile && echo 'export PATH=\$PATH:\$SONAR_SCANNER_HOME/bin' >> /etc/profile"
