---
- name: SonarQube Project and Token Automation
  hosts: your_ec2_instance
  become: true
  vars:
    sonarqube_port: 9000
    sonarqube_admin_login: "admin"
    sonarqube_admin_password: "admin123"
    sonarqube_project_key: "my_project"  # Change this to a unique key if necessary
    sonarqube_project_name: "My Project"
    sonarqube_token_name: "token_for_me"
    quality_gate_name: "Sonar way"  # Name of the quality gate
    public_ip: "18.219.11.171"
  tasks:
    - name: Wait until SonarQube Container is reachable via TCP/IP
      ansible.builtin.wait_for:
        host: localhost
        port: "{{ sonarqube_port }}"
        state: started
        delay: 5
        connect_timeout: 15
        timeout: 30

    - name: Check SonarQube to be healthy
      ansible.builtin.uri:
        url: "http://localhost:{{ sonarqube_port }}/api/system/health"
        user: "{{ sonarqube_admin_login }}"
        password: "{{ sonarqube_admin_password }}"
        method: GET
        force_basic_auth: yes
      register: response
      until: response.status == 200 and response.json.health == 'GREEN'
      retries: 20
      delay: 5

    - name: Check if the project already exists
      ansible.builtin.uri:
        url: "http://localhost:{{ sonarqube_port }}/api/projects/search?projects={{ sonarqube_project_key }}"
        user: "{{ sonarqube_admin_login }}"
        password: "{{ sonarqube_admin_password }}"
        method: GET
        force_basic_auth: yes
      register: existing_project_response

    - name: Debug existing project response
      debug:
        var: existing_project_response

    - name: Create a new project in SonarQube if it does not exist
      ansible.builtin.uri:
        url: "http://localhost:{{ sonarqube_port }}/api/projects/create?project={{ sonarqube_project_key }}&name={{ sonarqube_project_name | urlencode }}"
        user: "{{ sonarqube_admin_login }}"
        password: "{{ sonarqube_admin_password }}"
        method: POST
        force_basic_auth: yes
      register: project_response
      when: existing_project_response.json.paging.total == 0

    - name: Generate user token
      ansible.builtin.uri:
        url: "http://localhost:{{ sonarqube_port }}/api/user_tokens/generate"
        user: "{{ sonarqube_admin_login }}"
        password: "{{ sonarqube_admin_password }}"
        method: POST
        force_basic_auth: yes
        body: "name={{ sonarqube_token_name }}"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: token_response

    - name: Save token to a temporary file on remote
      ansible.builtin.copy:
        content: "{{ token_response.json.token }}"
        dest: "/tmp/sonarqube_token.txt"

    - name: Set the default quality gate
      ansible.builtin.uri:
        url: "http://localhost:{{ sonarqube_port }}/api/qualitygates/set_as_default"
        user: "{{ sonarqube_admin_login }}"
        password: "{{ sonarqube_admin_password }}"
        method: POST
        force_basic_auth: yes
        body: "name={{ quality_gate_name | urlencode }}"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: quality_gate_response
      failed_when: quality_gate_response.status not in [200, 204]

    - name: Create webhook
      ansible.builtin.uri:
        url: "http://localhost:{{ sonarqube_port }}/api/webhooks/create"
        user: "{{ sonarqube_admin_login }}"
        password: "{{ sonarqube_admin_password }}"
        method: POST
        force_basic_auth: yes
        body: "name=My Webhook&project={{ sonarqube_project_key }}&url=http://{{ public_ip }}/sonarqube-webhook/"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: webhook_response

    - name: Output project creation result
      debug:
        var: project_response

    - name: Output token generation result
      debug:
        var: token_response

    - name: Output quality gate configuration result
      debug:
        var: quality_gate_response

    - name: Output webhook creation result
      debug:
        var: webhook_response

